### ISSUE TITLE
Support for iOS9

### ISSUE THREAD

**Issue by catherjet** [luispadron/LPThumbnailView#1]
Since some 2.5% of devices still run iOS 9. supporting them might be necessary.

**Comment by luispadron** [comment]
Sure this would be nice, however, most of the project is written using the new iOS 10+ constraint anchors and I don't currently have the time to add support for older iOS versions.

Most major apps are dropping support for iOS 9 already, and don't see this feature helping much as it is a considerable amount of time required to get this working for iOS 9.0.

If you'd like to contribute and add support for iOS 9.0 using older constraints please feel free, I'll gladly review and merge good pull requests!

**Comment by luispadron** [comment]
closing because its stale
